version: '3.8'

services:
  claude-code-reverse:
    build: .
    ports:
      - '3456:3456'
    environment:
      - ENABLE_ROUTER=${ENABLE_ROUTER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
    restart: unless-stopped
